---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-exporter
  labels:
    app: se
    component: rabbit-exporter
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: se
    component: rabbit-exporter
    release: {{ .Release.Name }}
