---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "mongo-exporter.fullname" . }}
  labels:
    app: se
    component: mongo-exporter
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: se
      component: mongo-exporter
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongo-exporter
      labels:
        app: se
        component: mongo-exporter
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongo-exporter
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: mongo-exporter
          protocol: TCP
        env:
        - name: MONGODB_URL
          value: mongodb://{{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}:27017

