{
 "title": "Crawler_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Crawler site connection time 95th percentile",
   "type": "graph",
   "description": "Crawler site connection time 95th percentile",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_site_connection_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Crawler page parse time 95th percentile",
   "type": "graph",
   "description": "Crawler page parse time 95th percentile",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(crawler_page_parse_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Crawler site connection HTTP requests",
   "type": "graph",
   "description": "Crawler site connection HTTP requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_site_connection_time_count{kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Crawler page parse requests",
   "type": "graph",
   "description": "Crawler page parse requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_page_parse_time_count{kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of crawler page parse requests with error",
   "type": "graph",
   "description": "Rate of crawler page parse requests with error",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_page_parse_time_count{kubernetes_namespace=~\"$namespace\", http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of crawler site connection requests with error",
   "type": "graph",
   "description": "Rate of crawler site connection requests with error",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(crawler_site_connection_time_count{kubernetes_namespace=~\"$namespace\", http_status=~\"^[45].*\"}[1m])"
    }
   ]
  }
 ]
}