{
 "title": "UI_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Web page generation time 95th percentile",
   "type": "graph",
   "description": "Web page generation time 95th percentile",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(web_page_gen_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Web page HTTP requests",
   "type": "graph",
   "description": "Web page HTTP requests",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_page_gen_time_count{kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP requests with error",
   "type": "graph",
   "description": "Rate of UI HTTP requests with error",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(web_page_gen_time_count{kubernetes_namespace=~\"$namespace\", http_status=~\"^[45].*\"}[1m])"
    }
   ]
  }
 ]
}