---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: se
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: se
      component: rabbitmq
      release: {{ .Release.Name }}
  template:
    metadata:
      name: rabbitmq
      labels:
        app: se
        component: rabbitmq
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: rabbitmq
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: rabbitmq
          protocol: TCP
