---
- name: Delete k8s cluster
  hosts: localhost

  tasks:

    - name: Delete cluster
      shell: gcloud -q container clusters delete "search-engine" --zone "{{ zone }}"
      tags: skip_ansible_lint
