---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: se
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: se
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: se
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{ .Values.databasePort | quote }}
        - name: RMQ_HOST
          value: {{ .Values.RMQHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{ .Values.RMQQueue }}
        - name: RMQ_USERNAME
          value: {{ .Values.RMQUsername }}
        - name: RMQ_PASSWORD
          value: {{ .Values.RMQPassword }}
        - name: CHECK_INTERVAL
          value: {{ .Values.checkInterval | quote }}
        - name: EXCLUDE_URLS
          value: {{ .Values.excludeURLS }}
